---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule molecule-docker docker pytest-testinfra ansible-lint flake8 yamllint

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-linux-motd justereseau.linux_motd
  - cd justereseau.linux_motd

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks:
    urls:
      - "https://galaxy.ansible.com/api/v1/notifications/"
    on_success: change
